version: '2'
services:
  hello-world:
    image: tutum/hello-world
    ports:
      - 8000:80
    network_mode: "bridge"
    environment:
      SERVICE_TAGS: "green,service"
      SERVICE_80_CHECK_TIMEOUT: "2s"
      SERVICE_80_CHECK_INTERVAL: "5s"
      SERVICE_80_CHECK_HTTP: "/"
