version: '2'
services:
  hello-world:
    image: rchicoli/webapper
    expose:
      - 8080
    environment:
      SERVICE_TAGS: "green,service"
      SERVICE_80_CHECK_TIMEOUT: "2s"
      SERVICE_80_CHECK_INTERVAL: "5s"
      SERVICE_80_CHECK_HTTP: "/"
    depends_on:
      # - consul1
      # - consul2
      # - consul3
      # - registrator
      - elasticsearch
      - logstash
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.32.0.254:5002"
    networks:
      cluster:
        aliases:
          - webapper
