version: "2"
services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      cluster:
        aliases:
          - elasticsearch
    depends_on:
      - consul1
      - registrator

