version: "2"
services:
  elasticsearch:
    image: elasticsearch:5-alpine
    command: elasticsearch -E network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      cluster:
        aliases:
          - elasticsearch
