version: "2"
services:
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - consul1
      - registrator
    networks:
      cluster:
        aliases:
          - kibana
