version: '2'
services:
  registrator:
    image: gliderlabs/registrator:latest
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://localhost:8500
