version: '2'
services:
  registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500
    depends_on:
      - consul1
      - consul2
      - consul3
    networks:
      cluster:
        aliases:
          - registrator
